# Generated by Django 4.0.1 on 2022-01-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_api', '0002_alter_address_locality_alter_address_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone_no',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
